### ISSUE TITLE
Debug logging printed in @wasmer/wasi 0.11.0

### ISSUE THREAD

**Issue by ospencer** [wasmerio/wasmer-js#224]
Thanks again for publishing a new version!

It seems like there's one small issue. It looks like this bit of code: https://github.com/wasmerio/wasmer-js/blob/master/packages/wasi/src/index.ts#L1481 is uncommented in the latest release.

I couldn't find anywhere public to put a link to it, but in the bundled version of `@wasmer/wasi` from npm, in `/packages/wasi/lib/index.js` that bit of code looks like this:

![image](https://user-images.githubusercontent.com/7244034/81891145-ba728100-9575-11ea-97c5-95fae989cc96.png)

When I call WASI functions, I get this output:
```
WASI: wasiImport called: path_open (3,1,1041248,17,1,66,66,0,1040988)
WASI:  => 0
WASI: wasiImport called: fd_read (4,1040944,1,1040956)
WASI:  => 0
WASI: wasiImport called: fd_close (4)
WASI:  => 0
```

**Comment by syrusakbary** [comment]
I just published a fix version `0.11.1`, let me know if that fixes the issue :)

**Comment by ospencer** [comment]
Hmm. It looks like I'm still getting the same output and that block is still uncommented in `0.11.1`. :/

**Comment by syrusakbary** [comment]
It seems the build step was being skipped. I just published a patch version fixing it (`0.11.2`).
Let me know if this time things are good :)

**Comment by ospencer** [comment]
The CI passed! Thanks for resolving this so quickly! 😄
